supriya46788/Research-Paper-Organizer

Masthead.html, index.html
Fixed issue : #66 
Description:
The project currently lacks a dedicated section that introduces the team and vision behind the Research Paper Organizer. Adding a Masthead page will provide a professional, journal-style introduction that highlights the people and purpose driving the project.
Proposed Features:
Project Mission Statement: Briefly describe the purpose and goals of the tool.
Core Team Section: Names, photos, short bios, and roles of maintainers.
Advisors/Sponsors (if applicable): Recognition of any supporting individuals or organizations.
Contact Information: Email, GitHub repository link, or social media handles.
Launch Date & Version: Details about the current release version and initial launch date.
Why This Will Work:
Adds Professionalism: A dedicated masthead section …
=> Add Masthead Page to Showcase Project Mission & Team

tools.html
This PR fixes the issue where the Research and Tools cards were missing on the Tools Page.
Now, the page correctly displays all intended cards, ensuring better visibility of resources and improved user navigation.
fixed #222
=> Fixed Missing Research and Tools Cards on Tools Page

glossary.html, open-source.html
fixed issue: #213 
📖 Description:
The Glossary page provides a central place where users can look up definitions of key terms, concepts, and jargon related to research papers. Adding a "← Back to Home" button at the top ensures smooth navigation, allowing users to quickly return to the homepage without relying on browser navigation. The button is placed in a sticky header, so it remains visible even when users scroll through long lists of glossary terms.
✅ Why it Will Work:
Improved Navigation – Users don’t need to scroll back or use the browser’s back button. A single click takes them to the homepage.
Consistency – A sticky header matches modern UI patterns, keeping navigation elements accessible at all times.
Better UX – The button is clearly visible, styled with hover effects, and …
=> Back to home button on Glossary Page

contact.html
#356 Description:
This PR resolves the issue preventing users from submitting messages through the Contact Us form.
Changes Made:
Replaced blocking error modal with non-intrusive toast notifications:
✅ Success: “Message sent successfully!”
❌ Error: “Failed to send message. Please try again later.”
Added input validation (email format, required fields).
Improved UX by allowing users to continue interacting with the page while receiving feedback.
Why:
Previously, users were blocked by an error modal, preventing communication with support.
Toast notifications create a smoother, non-disruptive experience.
Steps to Verify:
Navigate to the Contact Us page.
Fill in valid details and click Send Message.
Confirm that:
Success toast appears and the message is delivered.
Invalid input triggers …
=> Fix Contact Us Form Submission with Toast Notifications

home.html
- Added the Chatbase chatbot with a working toggle button for mobile.
- The toggle button can open and close the chat window as expected.
- Button automatically positions itself below the chat window when open.
- Adjusted the chat window size so it’s not fullscreen on mobile
- Fixed most responsiveness issues with the chat window placement.
- The chatbot is inside an iframe, so getting the right classes and IDs for styling and JS was tricky.
- Because the navbar and top sections aren’t fully responsive yet, the initial viewport is wider than expected. This makes the toggle button appear slightly outside the screen initially.
- Once the top section and navbar are responsive, the chatbot will automatically align perfectly
---
---
=> Mobile-Responsive Chatbase Chatbot:

Masthead.html, css/glossary.css, glossary.html, js/glossary.js, open-source.html
📌 Changes
Implemented dark mode styling for the Open Source page masthead (header, repo cards, contribute section, acknowledgements, and footer consistency).
Added the Dark mode in the Glossary , Masthead , Open Source Pages.
Using the Sun Button You can Toggle the Dark Mode Vice versa
Updated Glossary page:
Glossary cards, example text, and content sections now adapt properly in dark mode.
Improved contrast for readability (titles, descriptions, example labels).
ScreenShots:
✅ Result
Consistent dark theme across Open Source and Glossary pages.
Better readability, improved UI aesthetics in low-light environments.
Closes Issue #353
=> Feature:Dark mode in Open Source, Masthead, and Glossary Pages

index.html
This PR removes the duplicate "Resources" block that was being rendered twice in the footer section.
Fixes: #394
---
---
=> Fixed duplicate "Resources" block in footer section

index.html
Purpose:
This PR updates the homepage loading screen so that the “Organizing your thoughts” messages appear only on the user’s first visit. Returning visitors skip the loading screen and see the main content immediately.
Fixes: #402
=> feat: show loading thoughts only on first visit and skip on return

signup.html
The Progress bar on sign-up page of "Password" was visible all time before the changes. But now, It is only visible when the input of "Password" is selected and also visible when the input is given. But, after the password is written and another input is selected then it again gets hidden.
Fixes: #455 
---
1. When the "Password" is not selected the progress bar is hidden.
2. When the "Password" is getting input, Progress-Bar is Visible.
3. When the "Password" is inputted and then the Progress-Bar gets hidden again.
---
Now, Progress bar is not shown/visible all time and only visible when the input option is selected and it is enhancing the UI.
=> Progress Bar Updated

css/glossary.css
Fixes #448 
I have fixed the UI for the Glossary item cards in the dark mode by using a better contrast of colors.
Fixes: #448 
---
Before:
After:
---
- [ ✅] My code follows the project’s guidelines and style.
- [✅ ] I have commented my code where necessary.
- [ ✅] I have updated the documentation if needed.
- [✅ ] I have tested the changes and confirmed they work as expected.
- [ ✅] My PR is linked to a GitHub issue.
=> Fix: UI for the Glossary Item Card in Dark Mode

css/glossary.css
Fixes #450 
The Mobile Toggle Menu Ui and Links was not visible earlier, in the dark mode. Now it is fixed. 
Changes in css/glossary.css file
Fixes: #450 
---
Before:
After:
---
=> Fix: Mobile Menu UI in Dark Mode

js/script.js
…471)
This PR fixes **Issue #471** – *Year Dropdown Shows Future Years*.
The year dropdown previously displayed years up to **2050**, which included years that have not yet occurred.
* Replaced the **hardcoded upper limit (2050)** with `new Date().getFullYear()`.
* Now the dropdown dynamically generates years from **1950 → current year**.
* Moved dropdown population so it only runs **once on page load**, preventing duplicate options.
---
**Before (buggy behavior):**
Dropdown included years beyond 2025 (up to 2050).
**After (fixed behavior):**
Dropdown stops at 2025 (the current year).
- [ ✅] My code follows the project’s guidelines and style.
- [ ✅] I have commented my code where necessary.
- [ ✅] I have tested the changes and confirmed they work as expected.
- [ ✅] My PR is linked to a …
=> Bug Fix: Year Dropdown Shows Future Years (closes #471)

js/script.js
… #470)
This PR fixes **Issue #470  – Year filter not updating immediately**.
- Previously, selecting a year did not refresh the papers list until another filter was changed.
- Added `onchange` event listeners for `minYear` (and `maxYear` if present).
- Now the papers list updates **instantly** when the year is selected.
**Fixes: #470 **
---
**Before:**  
User had to change another filter for year filter to apply.  
https://github.com/user-attachments/assets/9684f0b2-42aa-4908-9a6a-71bb58df0d9b
**After:**  
Papers refresh immediately when year is selected.  
https://github.com/user-attachments/assets/ec1dc8a9-d547-4f08-aa22-daf3cf6e6beb
- [ ✅] My code follows the project’s guidelines and style.
- [ ✅] I have commented my code where necessary.
- [ ✅] I have tested the changes and confirmed …
=> fix: refresh papers list immediately when year filter changes (closes #470)

landing.js
Fixes: #570 
---
https://github.com/user-attachments/assets/5f55a138-04cb-41ba-8b17-3f3fa78cded3
---
---
=> Smooth scroll from header for Features and How it works button.

css/auth.css
The line that is overlapping in login and signup pages have been fixed by placing the content in the center
Fixes: #583 
---
---
---
=> The line overlapping in login and signup pages have been fixed

css/auth.css
This PR addresses the issue where **Font Awesome icons disappear or blend into the background in dark mode**, making them invisible to the user. The icons remain visible in light mode.  
Fixes: #617
---
---
---
The issue specifically occurs in **dark mode**, where Font Awesome icons become invisible or blend with the background. This PR ensures they remain visible in **light mode**, while highlighting the need to fix dark mode visibility.
=> made buttons visible in dark mode

css/blog.css
Description
This pull request fixes the issue where the Blog page was not fully switching to dark mode, causing the navbar, footer, and content sections to appear inconsistent. The main changes include updating the CSS for dark mode compatibility across the Blog page and improving the styling of links, buttons, and cards for better readability and user experience.
The issue was reported in [Issue #629 ] (replace with the actual issue number), and this PR resolves it by ensuring that all Blog page UI elements correctly reflect dark mode styling and maintain layout consistency.
Type of change
Bug fix
How Has This Been Tested?
Tested locally by switching to dark mode and verifying the navbar, footer, and blog content sections render correctly.
Checked that links, buttons, and cards display …
=> [Bug Fix] – Dark Mode and Layout Issues on Blog Page

css/glossary.css
This pull request adds a hover effect for glossary cards to improve user experience and interactivity. The changes include updating the CSS to provide a smooth transition and highlighting effect when users hover over glossary cards.
The issue was reported in [Issue #666 ]  and this PR resolves it by ensuring glossary cards have a consistent hover effect across all pages.
Type of change
[x] New feature
How Has This Been Tested?
Tested locally by hovering over glossary cards in both light and dark modes.
Verified that the hover effect works consistently across different screen sizes.
Manually tested on Chrome, Firefox, and Edge to ensure cross-browser compatibility.
Ensured no other UI components were affected by the changes.
Checklist:
[x] My code follows the style guidelines of this …
=> [Feature] Add hover effect for glossary cards.

css/Tag-Based-filtering.css, css/open-source.css
Description:
This pull request fixes the inconsistent Navbar styling in dark mode on the Research Glossary, Open Source, and Tag-Based Filtering pages.
The issue was reported in [Issue #708 ]  and this PR resolves it by ensuring all affected pages render correctly and consistently in dark mode.
Type of change
Bug fix
How Has This Been Tested?
Verified locally in dark mode on Research Glossary, Open Source, and Tag-Based Filtering pages.
Confirmed the unintended white background no longer appears on the Open Source page.
Checked that element styling is now consistent across Open Source and Tag-Based Filtering pages.
Tested across multiple browsers (Chrome, Firefox, Edge) to ensure consistent behavior.
Ensured no regressions in light mode UI.
Checklist:
My code follows the style guidelines …
=> [BUG FIX] Styled elements properly in open source and tag based filtering page.

hemingway.html
**This PR fixes the dark mode toggle icon issue on the hemingway.html page**
**Improves clarity for users to know which mode is currently active.**
---
Attached in the issue raised regarding this
---
---
closes #754
=> Bug fix : Light/Dark Mode button not functional on hemingway.html

tools.html
Fixed the home icon on the footer of tools page.
Fixes: #763 
---
before:
after:
---
---
=> Fix: changed home icon on tools page footer

blog.html
**This PR fixes the alignment issue for blog cards when filtering by category. Previously, the cards were centered with uneven gaps. Now, they are aligned to the left with uniform spacing.**
Before : 
After : 
---
---
🙌 Additional Notes
- CSS change: justify-content: center → justify-content: flex-start in .blog-container.
- This improves layout consistency for all filtered categories.
closes #770
=> Bug Fix: Uniform Gaps between blog cards in blog.html

login.html
Description:
Added dark mode styling to the login/sign-in page, ensuring it matches the sign-up page theme.
This change fixes the issue where the login page remained in light mode even when dark mode was enabled on the home page.
Fixes: #704 
Type of change:
Bug fix
Checklist:
My code follows the project’s guidelines and style.
I have added CSS for .dark-mode to auth.css for login page.
I have added a script to auto-apply dark mode on page load based on localStorage.
I have tested the login page in both light and dark modes.
My PR is linked to a GitHub issue.
https://github.com/user-attachments/assets/8e9c2a3b-d130-4e22-99f9-a159e9a905fc
=> [BUG FIX] Dark mode fixed in sign in page.

landing.css
🚀 Pull Request
🔖 Description
My new card style has a darker blue border and a translucent light background, which gives it a clean look without any blur effect. It's a design that also works well for dark themes, providing a subtle and elegant visual style.
Fixes: # Issue No. 724
=> added glassy border

css/feedback.css, index.html
Fixed the feedback modal UI issues on mobile viewports **and added full dark/light mode support**.  
- The modal title is now centered.  
- The close icon (×) is correctly positioned at the top-right corner.  
- The "Submit" button is no longer obstructed by floating elements.  
- The modal now closes **only when the × button or Cancel button is clicked**, consistent with desktop behavior, preventing accidental closure when tapping anywhere else inside the modal on mobile.  
- In **dark mode**, the modal background, header, text, close icon, and form fields adapt to the dark theme for full readability. Light mode continues to display the modal in standard light colors.  
Fixes: #812
---
https://github.com/user-attachments/assets/f8112961-b829-4bc5-8436-8272c269c6fb
---
---
- Fixed JS so …
=> Fix feedback modal UI on mobile and add dark/light mode support

Faq.html, Masthead.html, Pdfconverter.html, Tag-Based-filtering.html, about.html, about_new.html, add-organize-papers.html, ats-checker.html, auth-callback.html, blog.html, contact.html, forgot-password.html, glossary.html, hemingway.html, home.html, index.html, login.html, offline.html, open-source.html, pdf-viewer.html, privacy.html, profile-settings.html, profile.html, roadmap.html, signup.html, summarize.html, terms-of-service.html, tools.html
Removed home icon from navbar, standardize favicons and improve page titles across all pages
Standardized the favicon setup across all 29 HTML pages in your Research Paper Organizer project. This involved fixing incorrect favicon paths, Updated 9 key pages with professional, branded titles that include consistent "| Research Paper Organizer" branding - most notably fixing the ATS Checker page which had a completely wrong title ("PDF Viewer & Annotator" instead of "ATS Resume Checker"), These changes ensure your website now has universal browser support for favicons, consistent professional branding across all pages, and a polished user experience with clear tab identification in browsers.
Fixes: #819
---
---
=> Removed home icon, standardize favicons, improved page titles

css/auth.css
This PR resolves the issue where the cross (×) icon disappeared on hover and was incorrectly positioned.  
The icon now remains visible on hover and has been repositioned to the top-right corner for improved UI/UX.  
Additionally, the Create Account button hover effect has been enhanced for consistency and responsiveness across all devices.
issue no. - #775 
---
---
=> Fix signup cross icon issue
