supriya46788/Research-Paper-Organizer

index.html
script.js
style.css

This PR introduces the following enhancements:
- Responsive layout for all viewports (mobile/tablet/desktop)
- Dark mode toggle with persistent theme switch
- Replaced default `alert()` with SweetAlert2 popups for better UX
- Organized the header section with new button layout
- Recorded Loom demo of the feature in action
🎥 Demo: [Watch here](https://www.loom.com/share/d63273d621984229a2781f24d303f155?sid=6e78d6ab-6410-4219-9653-b8a1f1922073)
Let me know if anything needs adjustment. Looking forward to your feedback!

UI enhancement

---

index.html
script.js
style.css

1. Local Storage Persistence
Implemented full Local Storage support to persist all user data including research papers, custom topics, and dark mode preference. This enhancement ensures that all papers and settings remain intact across browser sessions without requiring manual saving, providing a seamless and reliable user experience.
2. Dynamic Paper Upload & Preview
Added the ability to upload PDF files dynamically when adding or editing papers. Users can instantly preview the uploaded PDF within the modal before saving, enabling easier verification and management of documents. The uploaded PDFs are stored as Base64 data client-side and displayed in the paper details section with an embedded preview, improving workflow efficiency.

added local storage feature

---

index.html
style.css

issue number # 20 I have created the Footer. If there is any issue you can message me , I will resolve the problem as soon as possible

Footer Creation

---

index.html
script.js
style.css

Added Favorite icon

---

style.css

Description : 
The current color scheme of the website could be improved to enhance visual appeal, brand consistency, and accessibility.
Outcome:
A consistent, aesthetically pleasing color scheme.
Improved readability and accessibility for all users.
Issue #43 
Thankyou

improve color scheme

---

style.css

I made the ui design resposive.

Enchancement: Made UI changes 

---

contact.css
contact.html
contact.js
index.html

hey @supriya46788 ,
issue #40 
This PR adds a new Contact page to the project, styled consistently with the existing UI theme. It also updates the home page navbar to include a link to the Contact page, enabling easy access.
Changes:
Created a new contact.html page with a clean, accessible contact form.
Added contact.css with styles matching the main UI theme, including subtle animations and dark mode support.
Added contact,js for animations
Updated the main navbar component to include a Contact link.
Added smooth fade-in and underline animations on the Contact page for improved UX.
Ensured the form is accessible with proper labels and focus states.
please review it

 Add Contact Page with Matching UI 

---

index.html
script.js
style.css

Implemented a Rating and Favorite button for papers, allowing users to mark important items as favorites and optionally rate them. This enhances personalization and helps highlight high-quality resources.
fixed #81 #84

Fixed rate and favourite button

---

about.css
about.html
about.js
index.html

Issue: #54 
**Description:**
Create an About Us page that explains:
The purpose of the project (helping researchers organize, track, and cite papers efficiently).
Who built it (team members, contributors).
The tech stack used (React, JS, etc.).
How people can contribute or report issues.
**Why it will work:**
Builds trust → Users understand who created the tool and why.
Improves credibility → Especially important for open-source and academic tools.
Encourages contribution → Potential developers are more likely to join if they know the background and vision.
SEO benefits → An About page can help in search rankings.

Create an animative and responsive About Us page

---

index.html
script.js

Enabled the search bar functionality by making the search icon clickable and ensuring it opens/focuses the input field. Implemented JavaScript-based filtering logic to dynamically display results. Removed unused filters including year range, citation count, patent status, and author search to simplify the search experience and improve usability.
**Before:**
**After:**

Remove irrelevant search filters: To year, citation, patent, author

---

tools.html

Fixed Issue: #116 
**Description:**
A curated list of helpful research-related tools, websites, and templates that users can access directly from your platform. This can include:
Citation generators
Free academic journal databases
LaTeX/Overleaf templates
Plagiarism checkers
AI tools for summarizing or paraphrasing
Data visualization resources
**Why It Will Work:**
Centralized Hub: Saves users time searching for essential tools across the internet.
Beginner Friendly: New researchers can quickly find resources to improve their workflow.
Encourages Return Visits: Users will come back whenever they need a research-related tool.
Bonus Feature Ideas:
Tag/filter by tool type (e.g., Writing, Citation, Analysis).
Star/favorite tools for quick access.

Resources & Tools Page

---

blog.html

Implemented a navbar on the Blog page to ensure consistent navigation across the site. This improves the user experience by allowing seamless access to other sections directly from the Blog page.
fixed #162

Added Navbar to Blog Page

---

blog.html
css/blog.css

Successfully implemented a comprehensive dark mode feature and enhanced the blog page design with curved borders, improved navigation consistency, and a professional footer section.
Key Improvements:
🌓 Dark Mode Toggle: Added persistent dark/light theme switching with localStorage
🧭 Consistent Navigation: Integrated navbar across all pages for seamless user experience
🎨 Modern Design: Applied curved borders (20px radius) to all major sections
📱 Enhanced Footer: Multi-section footer with social links, quick navigation, and responsive design
💾 User Preference: Dark mode setting persists across browser sessions
📐 Responsive Layout: Mobile-optimized design that adapts to different screen sizes
The blog page now offers a polished, user-friendly experience with modern styling, consistent …

Enhanced Blog Page with Dark Mode & Improved Design

---

Faq.html
about.html
blog.html
contact.html
css/blog.css
css/faq.css
css/tool.css
home.html
index.html
tools.html

Improved the UI of the Tools page by enhancing layout, spacing, and styling for better readability and consistency. Also added a navbar to the Tools page to ensure smooth navigation across the site. This update makes the page more user-friendly and aligned with the overall project design.
fixed #168

Fixed UI on Tools Page and Added Navbar

---

tools.html

Fixed issue: #140 
Description:
Implement a footer at the bottom of the Resources and Tools page to provide quick access to important links and project information. The footer can include:
Quick Links – Navigation to Home, About, Contact, and FAQ.
Credits – Acknowledgement of contributors and open-source libraries used.
Social Media Icons – Links to community channels (GitHub repo, LinkedIn, etc.).
Copyright Notice – Year and project name.
This will ensure users don’t have to scroll back up to navigate and can quickly find relevant information.
Why It Will Work:
Improves Navigation – Users can jump to key sections without returning to the top.
Boosts Professionalism – A footer makes the page look complete and polished.
Increases Engagement – Social and repo links encourage community …

Add Footer to Resources & Tools Page

---

css/style.css

Fixed issue: #58 
Description:
Currently, the Research Paper Organizer interface displays content instantly without transition effects. Adding smooth animations for actions such as:
Paper card hover effects (slight scale-up, shadow transition)
Smooth fade-in when papers are loaded
Animated transitions when switching between light and dark mode
Button click animations (ripple or color fade)
Modal/popup animations when adding/editing papers
Why This Will Work:
Improved User Engagement: Smooth transitions make the interface feel more modern and enjoyable.
Better Visual Feedback: Animations help users understand the result of their interactions (e.g., clicking, hovering, switching modes).
Professional Look: Subtle animations improve the perceived quality of the project and make it stand out …

Add Smooth Animations to Enhance UI/UX

---

css/style.css
home.html
js/script.js

Reverts supriya46788/Research-Paper-Organizer#196

Revert "Improved user experience by making search terms visually stand out in…"

---

Faq.html
blog.html
contact.html
css/blog.css
css/contact.css
css/style.css
home.html
js/script.js

Reverts supriya46788/Research-Paper-Organizer#183

Revert "Implemented light and dark mode styles for all pages [Issue#124]"

---

css/contact.css

fix:Layout and Styling Bugs on Contact Page and Navbar

---

Faq.html
Masthead.html
about.html
blog.html
css/blog.css
css/glossary.css
glossary.html
home.html
index.html
js/glossary.js
open-source.html
roadmap.html
tools.html

Fixed Issue: #193 
Description
The Back-to-Top button provides users with a quick way to return to the top of the page after scrolling. It appears when the user scrolls down and smoothly scrolls them back to the header when clicked. This ensures better navigation, reduces user effort, and improves accessibility across the Research Paper Organizer project.
Why It Will Work
Improved User Experience: Users don’t need to manually scroll long pages.
Accessibility: Makes the site more user-friendly for people browsing long research content.
Consistency: Having the same button across all pages maintains a professional and unified look.
Mobile Friendly: Especially helpful on mobile devices where scrolling back up can be tedious.
Lightweight & Simple: Only requires minimal HTML, CSS, and JS.

Back-to-Top Button for All Pages

---

contact.html
css/contact.css
css/style.css

i have enhanced the contact page by keeping all the navbar at the top,footer at the bottom and input form at the middle and the input form has been enhanced by giving them display flex and giving them better padding .
Secondly,I have not raised this issue but solved the issue that there were two footers in the contact page so removed duplicate footer section too.
So it would be better if you could assign this pr as level 2 as i have solved 2 issues .
fixed #223

Fixed the contact page ui and removed duplicate footer

---

about_new.html
blog.html
css/about.css

This PR resolves the issue where the navbar on the About Us page looked different from other pages.
Now, the navbar is consistent across all pages with proper styling, alignment, button arrangement, and dark mode compatibility.
fixed #220

Fixed Navbar Inconsistency on About Us Page

---

tools.html

Resolved critical deployment issues preventing tools page functionality by converting absolute file paths to relative paths, ensuring proper loading of CSS styling and JavaScript functionality across all hosting environments.
Key Fixes Implemented:
📁 CSS Path Fix
📜 JavaScript Path Fix
🌐 Cross-Environment Compatibility: Ensured the page works both locally and when deployed to GitHub Pages/hosting platforms
🎨 Research Cards Display: Fixed the primary issue where tool cards weren't rendering when deployed
🔄 Consistent Behavior: Page now functions identically in development and production environments
Technical Impact:
✅ Deployment Ready: Tools page now displays properly on all hosting platforms
✅ Resource Loading: All CSS styles and JavaScript interactions work correctly when deployed
✅ No …

Fixed Asset Path Issues for Tools Page Deployment

---

css/auth.css
js/auth.js
js/form-validation.js
signup.html

- Real-time Form Validation: The form now validates fields as you type, providing instant feedback.
- Error Messages: Error messages are now displayed as simple text with an icon directly below the input fields.
- Password Strength Indicator: A visual indicator shows the strength of the password as you type.
- "Create Account" Button State: The "Create Account" button is now disabled until all fields are filled out correctly.
- Specific Password Requirements: The password must contain at least 8 characters, one uppercase letter, one number, and one special character. The requirements are only shown when the password field is focused, and the individual requirements turn green as they are met.
📸 **Screenshots:**  
<div align="center">
</div>  
Fixes #206

feat : Add Custom JS Validation to SignUp Page

---

glossary.html

Fixed issue: #212 
Description
The footer will serve as a clean, modern, and functional closing section of the glossary PAGE. It will provide quick access to important links, highlight the project’s identity, and offer contact and social connections. The new UI will balance minimalism with utility, ensuring the design complements the overall academic and professional theme of the Research Paper Organizer.
Why It Will Work
Professional Look: A clean footer adds credibility and aligns with the academic nature of the project.
Easy Navigation: Users can access key sections (About, Contact, Resources, Documentation, GitHub repo) quickly.
Consistency: Maintains brand identity across the project’s pages.
Responsive Design: Works seamlessly across all devices (desktop, tablet, mobile). …

Enhance footer UI on glossary page

---

index.html

The UI is enhanced even the circles have hover effect.

changed the UI #203

---

index.html
landing.css

✨ PR Title
Add Scroll-Based Fade & Slide Animations
📌 Description
This PR introduces smooth scroll-triggered animations across the landing page to make the UI more engaging and modern.
Elements now fade or slide into view as the user scrolls down, improving the overall user experience.
🔧 Changes Made
Added CSS animation classes:
fade-in → elements fade in on scroll
slide-left → elements slide in from the left
slide-right → elements slide in from the right
Implemented JavaScript Intersection Observer to trigger animations only when elements are visible in the viewport.
Applied animation classes to key sections:
Hero content & image
Feature cards (alternating slide left/right)
Steps in "How it Works"
Stats & testimonial cards
Call-to-action section
Ensured animations are lightweight and …

Feature:Added Animation in Landing Page

---

open-source.html

fixed issue: #211 
Description
The footer will serve as a clean, modern, and functional closing section of the Open Source Page. It will provide quick access to important links, highlight the project’s identity, and offer contact and social connections. The new UI will balance minimalism with utility, ensuring the design complements the overall academic and professional theme of the Research Paper Organizer.
Why It Will Work
Professional Look: A clean footer adds credibility and aligns with the academic nature of the project.
Easy Navigation: Users can access key sections (About, Contact, Resources, Documentation, GitHub repo) quickly.
Consistency: Maintains brand identity across the project’s pages.
Responsive Design: Works seamlessly across all devices (desktop, tablet, mobile). …

Enhance footer UI on Open Source page

---

glossary.html

fixed issue: #61 
Description:
Currently, the logo and title ("Research Paper Organizer") are displayed inline with other page elements. Adding a dedicated header section at the top will improve structure and navigation.
Why This Will Work:
Improved Branding: The logo will be consistently visible, reinforcing project identity.
Better Navigation: Key links will be accessible without scrolling to the footer.
Professional Look: A structured header is a hallmark of well-designed web apps.
User Experience: Sticky headers reduce the effort to move between sections, especially on long pages.
screenshot

Add Header with Logo 

---

js/auth.js

This closes the issue #279 
- In this PR I added email domain verification.
- This page will not accept email formats like abc@gml.com or xyz@abc.com
- It will only accept valid domains i.e gmail.com, yahoo.com, outlook.com, hotmail.com

Added email domain validation

---

landing.css

- Enhanced the .stat-item card styles with smoother transitions.
- Added a subtle shine animation on hover '
- Included a soft glowing border effect on hover for better visual feedback.
- Improved box-shadow and transform effects for a more dynamic interaction.
- Added overflow hidden to contain shine animation within the card.
Fixes : #300 
This update improves user experience by making the interactive cards on the Home page more engaging and visually appealing, contributing to a modern UI design.
Please merge this pull request.

Fixed : Enhancement : Adding hover effects on Home page

---

js/pdf-viewer.js
pdf-viewer.html

New Feature: Add Member Functionality
Implemented a new form to add members dynamically into the system.
Added input fields for Name, Email, and Role.
On submission, the data is stored and reflected in the Members List.
Integrated basic form validation to ensure required details are entered.
Updated UI for better user experience with "Add Member" button and modal form.
✅ Benefits
Makes it easier to manage members without manually editing data.
Improves usability and aligns with collaborative project needs.

updating the buttons

---

Faq.html
about.html
blog.html
contact.html
css/contact.css
css/faq.css
css/style.css
css/tool.css
index.html
landing.css
tools.html

Fixes #294 
I have resolved all the bugs that was in the footer section like cards were merging at different width of devices
Made the footer same at all pages
Added dark mode footer to all pages 
Just there was little confusion because the codes were in to many different files, but I have tried my best to give it proper look
After

Fixed all pages footer

---

docs/README.md

📋 **Description**
Updated the README.md file to include GSSoC’25 details and improve clarity for contributors.
> Fixed Issue #306  
- **Name**: Divya Jain
- **Email ID**: divya_239179@saitm.ac.in
-Verified the updated README renders correctly on GitHub.
- Checked that the logo displays properly 
**📸 Screenshots**
**✅ Checklist** 
---

Update Readme 

---

index.html
open-source.html

Description:
This PR updates the Research Paper Organizer website to use a light color scheme for a brighter and more readable UI. All sections, including the header, repo cards, contribute section, acknowledgements, and footer, have been updated with lighter backgrounds, vibrant accent colors, and soft shadows.
Changes include:
Body background changed to light (#f8fafc) and text color to dark (#1e293b)
Header gradient updated to soft blue tones
Repo cards, contribute cards, and acknowledgement cards use white/light backgrounds
Buttons and repo tags updated with vibrant blue accents
Footer updated with light cards and hover effects
Maintained responsive layout and animations
Screenshots:
Closes #284

Feature: Enhancement of Open Soucre Page + Animation

---

backend/package-lock.json
backend/package.json
backend/src/config/passport-setup.js
css/forgot-password.css
forgot-password.html
js/forgot-password.js
package.json

Hello, i made the changes to ui only, i didnt touch anything else except that.
The issue name is Enahncement: Reset password ui is inconsistent https://github.com/supriya46788/Research-Paper-Organizer/issues/181
The issue number is https://github.com/supriya46788/Research-Paper-Organizer/issues/181

Made ui changes for forgot-password only

---

index.html
landing.css
landing.js

So in this PR, I have adjusted the responsiveness of this website throughout all devices.

Responsiveness for landing page

---

index.html

#303 
Implemented a typewriter effect for the main heading: “Organize your Research Papers like Never Before” to make the landing page more dynamic and engaging.

Added typerwriter effect in heading

---

css/chatbot.css
home.html
js/chatbot.js

this pr addresses issue #335 
This PR introduces the complete chatbot UI and functionality:
- Header with close button (larger, with hover effect).
- Messages area.
- Input section for sending messages.
- **Design & Theme:** Fully matches the site’s look and feel with gradients, colors, and shadows.
- User messages aligned to the right with avatar showing initials from localStorage.
- Bot messages aligned to the left with distinct avatar color.
- Typing indicator implemented for the bot.
- Improved styling with soft background color, rounded corners, shadow, and focused state.
- User and bot avatars styled distinctly with visible circular design.
- All elements, including avatars, input, and messages, adjust colors correctly.
- Shifts slightly when chatbot opens so it doesn’t overlap with …

Add complete chatbot UI with avatars, dark mode, and input box styling

---

index.html
landing.css

🚀 Pull Request
🔖 Description
What: Updated hero to two-column grid, fixed animations, flat mockup, button styles, mobile stacking.
Why: Aligns UI with the provided landing page; improves readability and responsiveness.
I have also edited the testimonial card alignment.
Fixes: #301 
---
📸 Screenshots
After changes:
testimonial section:
Before:
After:
🙌 Additional Notes
This is my first pr. I'm a new contributor in gssoc'25. Thank you!

Redesign hero section: two-column layout, fixed animations, flat mock.

---

favicon/site.webmanifest
index.html
js/sw.js
offline.html
site.webmanifest

feat(pwa): add service worker, manifest, offline fallback

---

index.html

Issue - #354 
*Add marquee-style continuous carousel effect to testimonials*
- Implemented seamless infinite scroll animation for testimonial cards
- Added 5 testimonials with duplicate sets for continuous loop
- Enhanced card design with hover effects and gradient borders
- Added pause-on-hover functionality
- Optimized animation speeds: 10s desktop, 7.5s tablet, 6s mobile
- Improved responsive design and accessibility features
- Added fade edges with CSS masking for smooth transitions
https://github.com/user-attachments/assets/b122bfe5-ca91-4079-aced-946efd8fe258

Convert Testimonials section into an auto-scrolling carousel

---

summarize.html

Actually the problem is that may be the correct backend url at which you have deployed the application is not available
so i have changed one line in summarize.html
make sure to change that url with your backned deployed url
after changing it will work 
Thanks

Update API endpoint in summarize.html to use production URL #243 issue

---

Faq.html
about.html
about_new.html
blog.html
glossary.html
home.html
index.html
js/glossary.js
tools.html

Fix: added a scroll to bottom arrow
Fixes: # (issue number)
343
1. Implemented a floating button for scroll-to-top and scroll-to-bottom functionality  
2.  Arrow icon dynamically changes direction based on scroll position  
3. Added hover effect for better UI  
4.  Button hidden when not required (less scroll)

Fix: add scroll to bottom arrow issue#343

---

Tag-Based-filtering.html

🛠 Summary
This PR introduces two key improvements:
Dark Mode Toggle Fix
Sun (☀️) and Moon (🌙) icons now toggle correctly.
User preference is stored in localStorage.
Dark/light mode persists after page refresh.
Modern Footer Addition
Added a responsive footer with three sections:
Quick Links (Home, About Us, Contact, FAQ)
Resources (Blog, Glossary, Open Source)
Connect (GitHub, LinkedIn, Email icons)
Clean grid layout with hover effects.
Fully responsive and adapts to dark mode seamlessly.
ScreenShots:
Closes #396

Bug:Solved the Dark Mode Problem & Added the Footer

---

home.html

Successfully implemented a unified modern footer design across the home page to match the about page, ensuring consistent branding, navigation, and visual aesthetics throughout the entire website.
Visual Impact:
Consistent Brand Identity: All pages now share the same professional footer design
Enhanced Navigation: Users can easily access key pages from any footer location
Modern Aesthetics: Beautiful blue gradient background with glass-morphism card effects
Mobile Optimized: Perfect responsive behavior across all screen sizes
Interactive Experience: Engaging hover effects and smooth transitions
This fix ensures the Research Paper Organizer maintains a cohesive, professional appearance with consistent navigation and branding elements across all pages, creating a seamless user experience …

Fixed Footer of home page

---

docs/README.md

This PR addresses issue #426 
Added the missing anchor so the "Back to Top" badge at the end of the README that redirects users back to the top of the file for easier navigation.

Add back to top redirection in readme.md

---

blog.html

**Summary of Changes:**
1. HTML (<header>):
- A new <div class="search-container"> has been added right below your header's paragraph.
- This container holds an icon (<i class="fas fa-search">) and the search <input type="search" id="searchInput">.
- The input has a placeholder and an aria-label for better accessibility.
2. CSS (<style> block):
- New styles for .search-container, #searchInput, and the search icon have been added.
- These styles create a modern, rounded search bar that fits the page's aesthetic.
- :focus and :focus-within states are included for better user interaction.
- Dark mode styles have also been added to ensure the search bar looks good in both themes.
3. JavaScript (<script> block):
- The original category filtering logic has been replaced and upgraded.
- A new …

search functionality implementation

---

login.html
signup.html

This PR adds a ✖ button on both login and signup pages to allow users to return to the previous page.
Fixes: #465 
---
Improves navigation by providing a quick, intuitive way to go back without relying on the browser back button.
Before:
https://github.com/user-attachments/assets/186aba3f-7e50-4a11-898c-07e336617dd7
After:
https://github.com/user-attachments/assets/dc16b691-b91c-466d-aaac-bd54881abfc0
---
•	Added window.history.back() button in login.html & signup.html
•	Styled button for top-left placement

Add ✖ back button to login and signup pages

---

ats-checker.html
css/ats-checker.css

hello!
this PR enhances the UI of the ATS Resume Score Checker Page
Fixes #468 
Contributor Information:
Name: Suranjana Paul
Email ID: paulsuranjana64@gmail.com
Type of Change: UI/UX improvement
the changes made are:
1.  Changed the UI to look more professional
2. wrapped the input section and score sections into cards
3. changed the default basic look of the page
previous:
new: 
https://github.com/user-attachments/assets/620022a1-5678-4d22-8c70-52ba9ed8bda2
all changes have been tested and reviewed to ensure functionality. i’d love your feedback and am happy to make further adjustments if needed. thanks for the opportunity!

Enhanced the UI of the ATS Resume Score Checker Page

---

Tag-Based-filtering.html
home.html

Fixes: # (issue number)
---
---
---
Please review the changes and merge the pull request.
https://www.loom.com/share/778edb2094124004a36281aa4768239d?sid=0c570a22-ea21-4f93-943f-9a52be313dcf

Added scroll top-to-bottom and bottom-to-top button

---

about.html
contact.html
index.html
privacy.html

Added the privacy policy page 
Fixes: #434 
---
---
---

Added Page for the privacy policy

---

Tag-Based-filtering.html

Fixes #488 
I have removed the redundant features from the tag-based-filtering.html page.
Fixes: #488 
---
Before:
After:
---
---

Fix: Tag Suggestion Form and Cloud Sync Form Removed from the Tag Based Filtering Page

---

css/style.css
index.html

Added a typing-style fade-up animation to the hero section heading.  
Each line of the text now appears letter by letter with a smooth fade-up effect.
This improves the visual appeal and draws more attention to the hero message.  
Fixes: #493 
---
[textanimation1.webm](https://github.com/user-attachments/assets/fc586292-0f4b-4cfa-a474-a302dbb3eeb2)
---
*Before:* Static text in hero heading.  
*After:* Animated text with sequential fade-up.
- [✅ ] My code follows the project’s guidelines and style.
- [✅ ] I have commented my code where necessary.
- [✅ ] I have updated the documentation if needed.
- [✅ ] I have tested the changes and confirmed they work as expected.
- [ ✅] My PR is linked to a GitHub issue

Added a text animation

---

Faq.html
Masthead.html
Tag-Based-filtering.html
about.html
about_new.html
ats-checker.html
blog.html
contact.html
glossary.html
home.html
open-source.html
pdf-viewer.html
privacy.html
signup.html
summarize.html
terms-of-service.html
tools.html

Fixes: # 378
All the checklists are fulfilled

feature_favicon

---

js/pdf-viewer.js

Added an eraser function to pdf viewer with option to adjust the size of Eraser . This will help user to use Pen tool efficently .
Fixes: #492 
---
---
---

Added Eraser functionality to pdf viewer .

---

.github/workflows/pr-merged-automate-message.yml

Added workflows for a thank you 

---

css/style.css
index.html
landing.css

Improved navbar toggle dessign in mobile screens
Fixes: #536 
---
---

improved navbar in mobile devices

---

index.html
landing.css

I have added the html and css for a hamburger menu on the landing page and its functionalities are already defined.
Fixes: #558 
---
---
---

Added hamburger menu on the home page

---

docs/README.md

fix the file format in README

---

css/style.css
home.html
landing.css

I have made the navbar of the home page to sticky such that it remains even while scrolling.
Fixes: #561 
---
---
---

Made the navbar sticky for the home page

---

about.html
css/about.css
css/contact.css
css/style.css

##solved #529 
1->fix olor of toggle theme light 
2-.fix color of navBar on hover of contact in ligth mode
2->added leaderboard
Fixes: #529 
---
---
- [✅] My code follows the project’s guidelines and style.
- [✅] I have commented my code where necessary.
- [✅] I have updated the documentation if needed.
- [✅] I have tested the changes and confirmed they work as expected.
- [✅ ] My PR is linked to a GitHub issue.
---

fix colors In toggle button and contact navBar in light theme and added leaderBoard

---

Faq.html
css/faq.css

This PR improves the chatbot on the **FAQ page** by replicating the exact implementation from the **Homepage**. The chatbot now matches the project’s theme colors, design, and behavior across both pages.
---
* **Faq.html** – Replaced existing chatbot implementation with the homepage version
---
* ❌ Black default theme
* ❌ Different look from homepage chatbot
* ✅ Matches homepage chatbot
* ✅ Integrated project theme
---
The FAQ page chatbot now:
* Looks **identical to homepage chatbot**
* Fully aligns with **project theme**
* Provides a **unified experience** across the site
* Works **reliably on desktop and mobile**
---
✅ **Status: Completed** – Chatbot implementation successfully fixed on FAQ page
---
@supriya46788 I am a GSSoC ’25 contributor and I have successfully completed the …

Fixed Chatbot theme on FAQ Page

---

css/tool.css

Hi @supriya46788 ,
I made some UI/UX improvements in the Tools section:
Added box-shadow for better depth and visibility.
Applied border-radius for smoother and modern design.
Kindly review the changes and let me know if further improvements are needed 🙂

improved tools section

---

css/tool.css

Reverts supriya46788/Research-Paper-Organizer#597

Revert "improved tools section"

---

docs/CONTRIBUTING.md

This PR improves the **Code of Conduct** by making it more engaging, visually appealing, and beginner-friendly.  
The enhancements include:  
- 🏷️ **Badges** to highlight key sections and make them easily scannable.  
- 🎉 **Emojis** to add a friendly and welcoming tone throughout the document.  
- 🎬 **GIFs** in each section to create a more interactive and fun reading experience.  
All the original information and guidelines have been preserved exactly as they were — only the presentation and formatting have been enhanced to make the CoC more attractive, contributor-friendly, and aligned with open-source community standards.

Enhanced CoC with badges, emojis, and GIFs

---

about.html
about_new.html
add-organize-papers.html

Fixes: # (issue number)
---
---
---

Added Favicon Link

---

js/form-validation.js
signup.html

Added a lowercase condition in password checklist.
Fixes: #630 
---
---
---

Added a lowercase condition in password checklist

---

index.html

Reverts supriya46788/Research-Paper-Organizer#700

Revert "📦 [Feature Add] Integrating Chatbot for better navigation"

---

css/tool.css
js/tools.js
tools.html

This pull request introduces a "Favorite Tools" feature. Users can now bookmark their most-used tools by clicking a star icon on each tool card. Their selections are saved and displayed in a new personalized "Your Study Toolbox 📚🧰" section at the top of the page for quick and easy access.
Fixes: #694  
---
---
- [✅] My code follows the project’s guidelines and style.
- [✅] I have commented my code where necessary.
- [✅] I have tested the changes and confirmed they work as expected.
- [✅] My PR is linked to a GitHub issue.
---
I'm excited to contribute this feature as part of my participation in the GirlScript Summer of Code (GSSoC) 2025. I learned a great deal about using localStorage and handling DOM events while building this. I'm looking forward to any feedback! 😊

Feature-A personalized feature of favorite tools achieved 

---

add-organize-papers.html
backend/package-lock.json
css/add-organize-papers.css

close : #690 
This PR implements the file preview feature on the Add Papers page. Now, when users upload files:
- They can see a preview button next to the uploaded file.
- Clicking the preview button shows the image or PDF preview.
Fixes: #690 
---
| Before Upload | After Upload (Preview Button) | After Clicking Preview |
|---------------|------------------------------|----------------------|
| <img width="1366" height="717" alt="OI" src="https://github.com/user-attachments/assets/3acd18e0-6c08-4708-ba08-549a1340150e" /> | <img width="1366" height="768" alt="Screenshot (980)" src="https://github.com/user-attachments/assets/9893f729-b30c-4b73-a421-1a413c1928b1" /> <br> 👁️ Preview Button | <img width="1366" height="768" alt="Screenshot (981)" …

Completed add file preview feature

---

contact.html

This pull request adds validation for the Name field in the contact form.
Ensures that only letters and spaces are allowed.
Displays an inline error message if invalid characters (numbers/symbols) are entered.
Prevents form submission until the input is corrected.
Fixes: #709 
---

Fix name validation

---

Faq.html
css/faq.css
css/tooltip.css
home.html
index.html
js/faq.js
js/tooltip.js

Added tooltips to key interactive elements on the **Research Paper Organizer** page to improve usability. Tooltips provide concise guidance on hover, making the app more intuitive and user-friendly. Implemented using **tooltip.css** and **tooltip.js** for consistent styling and behavior.
⚠️ Note: Opening `home.html` currently results in `Cannot GET /landing.html`. This seems related to routing or file path issues and should be investigated.
Fixes: #743
---
Could not provide screenshots as `home.html` is not opening and shows `Cannot GET /landing.html`.
---
---
- Tooltips enhance user experience without cluttering the interface.  
- Beginner-friendly feature; can be extended incrementally.  
- Hovering over interactive elements now shows concise, user-friendly descriptions.

Add tooltips

---

home.html
open-source.html
privacy.html
terms-of-service.html

Fixed the home icon on the footers of privacy, home, tos, open source pages
Fixes: #783 
---
---
---

Fix: fixed the home icon on the footer

---

Tag-Based-filtering.html

On the " Research Paper Organiser" page where demo cards are added, there some space was empty for the 3 cards and even some combinations were missing. So, new 3 cards are made with the new combinations and even teh free space is used, which shows the users some new examples with different combination too.
Fixes: #767 
---
---

New 3 Cards Added

---

blog.html

fixed all btns with blue color as you requested
Fixes: # Issue No.795

fixed buttons with blue color

---

css/feedback.css
index.html

I have aligned the feedback button with the backtotop button
Fixes: #805 
---
---
---

Fix: Aligned feedback button (fixed #805)

---

css/feedback.css

I have fixed the feedback button placement on mobile view and also fixed the glitch you mentioned when clicking/hovering the button.
Fixes: # (issue number)
---
https://github.com/user-attachments/assets/8f8f62d1-9eee-409d-b783-40df96ce6ce5
---
---

Fix feedback button

---

about.html
blog.html
css/contact.css
css/faq.css
css/tool.css
terms-of-service.html

I have fixed the social icons on the footers. 
I had noticed that the favicon of the tos page wasn't visible, fixed that as well.
Fixes: #806 
---
---
---

Fix footer icon

---

css/tool.css

Reverts supriya46788/Research-Paper-Organizer#831

Revert "hovering effect added"
